### ISSUE TITLE
Field 'teaser_image_size_id' doesn't have a default value

### ISSUE THREAD

**Issue by Kyorben** [heimseiten/contao-page-teaser-bundle#1]
Beim erstellen einer neuen Seite kommt folgender Fehler:

An exception occurred while executing 'INSERT INTO tl_page (`cuser`, `cgroup`, `chmod`, `pid`, `sorting`, `tstamp`) VALUES (0, 0, 'a:9:{i:0;s:2:\"u1\";i:1;s:2:\"u2\";i:2;s:2:\"u3\";i:3;s:2:\"u4\";i:4;s:2:\"u5\";i:5;s:2:\"u6\";i:6;s:2:\"g4\";i:7;s:2:\"g5\";i:8;s:2:\"g6\";}', 3, 128, 0)': SQLSTATE[HY000]: General error: 1364 Field 'teaser_image_size_id' doesn't have a default value

**Comment by heimseiten** [comment]
Leider kann ich den Fehler nicht nachvollziehen. Im DCA ist ein Defaultwert definiert. Bitte mal probieren, ob es mit der neuen Version 1.1.6 funktioniert. Ansonsten mal mit einer frischen Version ohne andere Erweiterung ausprobieren.

**Comment by Kyorben** [comment]
Danke, die Erweiterung funktioniert nun in der neuen Version.
